{
  name: "PR & Push",
  on: {
    push: {
      branches: [ "main" ]
    },
    pull_request: {
      branches: [ "main" ]
    }
  },
  jobs: {
    build: {
      runs-on: "ubuntu-latest",
      strategy: {
        matrix: {
          node_version: [ 10, 12, 14, 16 ]
        }
      },
      steps: [
        { uses: "actions/checkout@v2" },
        {
          name: "Node v${{ matrix.node_version}}",
          uses: "actions/setup-node@v2",
          with: {
            node-version: "${{ matrix.node_version }}"
          }
        },
        { run: "yarn" },
        { run: "yarn lerna run compile" },
        { run: "yarn lerna run test" },
      ],
      env: {
        CI: true
      }
    }
  }
}

