{
  name: "Release",
  on: {
    release: {
      types: [ "created" ]
    }
  },
  jobs: {
    publish: {
      runs-on: "ubuntu-latest",
      steps: [
        {
          uses: "actions/checkout@v2",
          with: {
            ref: "${{ env.GITHUB_REF }}"
          }
        },
        {
          name: "Set up node 12",
          uses: "actions/setup-node@v2",
          with: {
            registry-url: "https://registry.npmjs.com",
            node-version: "12"
          }
        },
        { run: "yarn" },
        { run: "yarn lerna run compile" },
        { run: "yarn lerna run test" },
        {
          run: "node_modules/.bin/lerna publish from-package --yes",
          env: {
            NODE_AUTH_TOKEN: "${{ secrets.NPM_PUBLISH_TOKEN }}"
          }
        },
      ]
    }
  }
}

